allowBuilds:
  '@parcel/watcher': true
  '@prisma/engines': true
  '@scarf/scarf': true
  '@swc/core': true
  esbuild: true
  msgpackr-extract: true
  prisma: true
  protobufjs: true
  unrs-resolver: true
  workerd: true
